### ISSUE TITLE
multiword_expressions_service.py missing

### ISSUE THREAD

**Issue by pierregreborio** [blackbirdco/time_extract#2]
The file multiword_expressions_service..py sem to be missing from the repository.

**Comment by bfcamara** [comment]
It's definitely missing.

**Comment by zaratan** [comment]
Wow. I'll see if I can find it. @AurelieMerlot do you have it?

**Comment by zaratan** [comment]
It was something I was working on/with 3 years ago. I may have it lingering somewhere but really unsure.

**Comment by bfcamara** [comment]
@denispasin Thank you. I am very interested in this library and the work you have done. How far did you go with your work? Was this library really used in Jam? Did you achieve good results?

I am asking this because I am currently building a bot that heavily relies on dates and times, and none of the libraries out there (SUTime, GUTime, HeidelTime, IBM Watson, Microsoft Recognizer, etc.) support exclusions (anything but friday) or grouping (only on tuesday or thrusday).

One thing that I am thinking is to port this library to C#, and to support the English language. But I would love to make this library work first, add support to english  on it, and finally do the port.

**Comment by zaratan** [comment]
We did use it in prod for auto-tagging of messages: https://www.aclweb.org/anthology/C16-2023.pdf

**Comment by zaratan** [comment]
(I'm not part of Jam anymore, hence the fact that I might not have that code anywhere :| )

**Comment by zaratan** [comment]
Be careful that it's a wrapper around treetagger and you might want to update the Dockerfile.

**Comment by AurelieMerlo** [comment]
Sorry @pierregreborio and @bfcamara, I just saw your messages.
I look today if I find the file.

**Comment by zaratan** [comment]
I don't have it… The directory containing this project was "cleaned" when I left the company.

**Comment by zaratan** [comment]
@bfcamara and @pierregreborio : @AurelieMerlo has found the file \o/ Thanks a lot ❤️
